---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks: 
  
    - name: Download Jenkins to container
      raw: wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
    - name: Add a repository
      raw: echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list
    - name: Update
      raw: apt-get update
    - name: Install Jenkins
      raw: apt-get install jenkins
    - name: To show the password
      raw: cat /var/lib/jenkins/secrets/initialAdminPassword

