 hosts: Jenkins
  gather_facts: false
  remote_user: root
   "tasks": 
    - name: Update and upgrade all
      apt:
        upgrade: true
        update_cache: true
        allow_unauthenticated: true
