---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks: 
  
    - name: Download Jenkins to container
      raw: wget -q -O - http://pkg.jenkins-ci.org/debian-stable/jenkins-ci.org.key | apt-key add
    - name: Add a repository
      raw: echo "deb http://pkg.jenkins-ci.org/debian binary/" > /etc/apt/sources.list.d/jenkins.list
    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true
    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade || true
    - name: Install Jenkins
      raw: apt install jenkins
