---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks: 
    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade || true
    - name: Hello Jenkins
      raw: echo Jenkins is installed on your PC!
