---

- hosts: Jenkins
  gather_facts: false
  remote_user: root
  tasks: 

    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade || true


