---
- hosts: all
  remote_user: root
  gather_facts: false
  tasks: 
    - name: Update
      raw: apt-get -y --allow-unauthenticated update || true

    - name: Upgrade
      raw: apt-get -y --allow-unauthenticated upgrade || true
    - name: forward DNS traffic, but do not open firewall
      local_action:
        internal_port: 80
        external_port: 8080
        protocol: http
